// ESP8266 Home Automation v1.0 — Arduino IDE sketch (GENERATED FILE).
// Generated by tools/mirror_to_ino.py from src/. Do not edit by hand.
//
// Install via Library Manager: WiFiManager (tzapu), NTPClient, Time (PaulStoffregen).
// Board: "Generic ESP8266 Module", Flash Size 4M, FS: LittleFS.
// Tweak the two defines below for your relay board, then upload.

#define RELAY_ACTIVE_LOW 1
#define DEVICE_NAME "esp-home"

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiClient.h>
#include <WiFiManager.h>
#include <NTPClient.h>
#include <TimeLib.h>
#include <ESP8266WebServer.h>
#include <Updater.h>
#include <ArduinoOTA.h>
#include <LittleFS.h>
#include <WiFiUdp.h>

// Forward declarations: full definitions are concatenated below.
// Needed because the IDE hoists function prototypes above the point where
// these structs are defined. RULE for contributors: free functions in device
// code must not use custom types in their signatures unless the type is
// forward-declared here (see docs/PRACTICES.md).
struct AppContext;
struct RtcSlot;
// ===== src/common/sha256.h =====
// Compact public-domain SHA-256 (Brad Conte style, rewritten here).
// Used for salted password hashing. Verified against NIST vectors in tests.
#include <cstddef>
#include <cstdint>

#define HA_SHA256_BLOCK_SIZE 32

typedef struct {
  uint8_t data[64];
  uint32_t datalen;
  uint64_t bitlen;
  uint32_t state[8];
} HA_SHA256_CTX;

void ha_sha256_init(HA_SHA256_CTX *ctx);
void ha_sha256_update(HA_SHA256_CTX *ctx, const uint8_t *data, size_t len);
void ha_sha256_final(HA_SHA256_CTX *ctx, uint8_t hash[HA_SHA256_BLOCK_SIZE]);

// Convenience: hex digest of a byte string.
void ha_sha256_hex(const uint8_t *data, size_t len, char out_hex[65]);
// ===== src/common/sha256.cpp =====
#include <string.h>

#define ROTLEFT(a, b) (((a) << (b)) | ((a) >> (32 - (b))))
#define ROTRIGHT(a, b) (((a) >> (b)) | ((a) << (32 - (b))))
#define CH(x, y, z) (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define EP0(x) (ROTRIGHT(x, 2) ^ ROTRIGHT(x, 13) ^ ROTRIGHT(x, 22))
#define EP1(x) (ROTRIGHT(x, 6) ^ ROTRIGHT(x, 11) ^ ROTRIGHT(x, 25))
#define SIG0(x) (ROTRIGHT(x, 7) ^ ROTRIGHT(x, 18) ^ ((x) >> 3))
#define SIG1(x) (ROTRIGHT(x, 17) ^ ROTRIGHT(x, 19) ^ ((x) >> 10))

static const uint32_t k[64] = {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
    0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
    0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
    0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
    0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2};

static void sha256_transform(HA_SHA256_CTX *ctx, const uint8_t data[64]) {
  uint32_t a, b, c, d, e, f, g, h, i, t1, t2, m[64];
  for (i = 0; i < 16; ++i)
    m[i] = ((uint32_t)data[i * 4] << 24) | ((uint32_t)data[i * 4 + 1] << 16) |
           ((uint32_t)data[i * 4 + 2] << 8) | ((uint32_t)data[i * 4 + 3]);
  for (; i < 64; ++i) m[i] = SIG1(m[i - 2]) + m[i - 7] + SIG0(m[i - 15]) + m[i - 16];
  a = ctx->state[0]; b = ctx->state[1]; c = ctx->state[2]; d = ctx->state[3];
  e = ctx->state[4]; f = ctx->state[5]; g = ctx->state[6]; h = ctx->state[7];
  for (i = 0; i < 64; ++i) {
    t1 = h + EP1(e) + CH(e, f, g) + k[i] + m[i];
    t2 = EP0(a) + MAJ(a, b, c);
    h = g; g = f; f = e; e = d + t1;
    d = c; c = b; b = a; a = t1 + t2;
  }
  ctx->state[0] += a; ctx->state[1] += b; ctx->state[2] += c; ctx->state[3] += d;
  ctx->state[4] += e; ctx->state[5] += f; ctx->state[6] += g; ctx->state[7] += h;
}

void ha_sha256_init(HA_SHA256_CTX *ctx) {
  ctx->datalen = 0; ctx->bitlen = 0;
  ctx->state[0] = 0x6a09e667; ctx->state[1] = 0xbb67ae85;
  ctx->state[2] = 0x3c6ef372; ctx->state[3] = 0xa54ff53a;
  ctx->state[4] = 0x510e527f; ctx->state[5] = 0x9b05688c;
  ctx->state[6] = 0x1f83d9ab; ctx->state[7] = 0x5be0cd19;
}

void ha_sha256_update(HA_SHA256_CTX *ctx, const uint8_t *data, size_t len) {
  for (size_t i = 0; i < len; ++i) {
    ctx->data[ctx->datalen++] = data[i];
    if (ctx->datalen == 64) {
      sha256_transform(ctx, ctx->data);
      ctx->bitlen += 512;
      ctx->datalen = 0;
    }
  }
}

void ha_sha256_final(HA_SHA256_CTX *ctx, uint8_t hash[HA_SHA256_BLOCK_SIZE]) {
  uint32_t i = ctx->datalen;
  if (ctx->datalen < 56) {
    ctx->data[i++] = 0x80;
    while (i < 56) ctx->data[i++] = 0x00;
  } else {
    ctx->data[i++] = 0x80;
    while (i < 64) ctx->data[i++] = 0x00;
    sha256_transform(ctx, ctx->data);
    memset(ctx->data, 0, 56);
  }
  ctx->bitlen += (uint64_t)ctx->datalen * 8;
  ctx->data[63] = (uint8_t)(ctx->bitlen);
  ctx->data[62] = (uint8_t)(ctx->bitlen >> 8);
  ctx->data[61] = (uint8_t)(ctx->bitlen >> 16);
  ctx->data[60] = (uint8_t)(ctx->bitlen >> 24);
  ctx->data[59] = (uint8_t)(ctx->bitlen >> 32);
  ctx->data[58] = (uint8_t)(ctx->bitlen >> 40);
  ctx->data[57] = (uint8_t)(ctx->bitlen >> 48);
  ctx->data[56] = (uint8_t)(ctx->bitlen >> 56);
  sha256_transform(ctx, ctx->data);
  for (i = 0; i < 4; ++i)
    for (uint32_t j = 0; j < 8; ++j)
      hash[i + j * 4] = (uint8_t)((ctx->state[j] >> (24 - i * 8)) & 0xff);
}

void ha_sha256_hex(const uint8_t *data, size_t len, char out_hex[65]) {
  static const char *digits = "0123456789abcdef";
  uint8_t hash[HA_SHA256_BLOCK_SIZE];
  HA_SHA256_CTX ctx;
  ha_sha256_init(&ctx);
  ha_sha256_update(&ctx, data, len);
  ha_sha256_final(&ctx, hash);
  for (int i = 0; i < HA_SHA256_BLOCK_SIZE; ++i) {
    out_hex[i * 2] = digits[(hash[i] >> 4) & 0xf];
    out_hex[i * 2 + 1] = digits[hash[i] & 0xf];
  }
  out_hex[64] = '\0';
}
// ===== src/logic/clock.h =====
// Clock abstraction: device uses ::millis(), tests inject a manual clock.
#include <cstdint>

namespace ha {

class IClock {
 public:
  virtual ~IClock() = default;
  virtual uint32_t millis() const = 0;
  virtual uint32_t epoch() const = 0;  // seconds since 1970, 0 = unknown
};

}  // namespace ha
// ===== src/logic/relay.h =====
// Relay bank: logical ON/OFF state decoupled from physical pin level,
// so active-LOW relay modules are handled in one place.
#include <cstdint>
#include <functional>

namespace ha {

class RelayBank {
 public:
  static const int kMaxChannels = 8;

  RelayBank();

  void configure(int channels, bool active_low);
  int channels() const { return channels_; }
  bool activeLow() const { return active_low_; }

  bool set(int ch, bool on);   // returns false if ch out of range
  bool toggle(int ch);
  bool get(int ch) const;      // logical state; false if out of range

  // Physical pin level for a logical state (HIGH=1 / LOW=0).
  int levelFor(bool on) const { return (on != active_low_) ? 1 : 0; }
  int levelForChannel(int ch) const;

  using ChangeCb = std::function<void(int ch, bool on)>;
  void onChange(ChangeCb cb) { change_cb_ = cb; }

 private:
  bool valid(int ch) const { return ch >= 0 && ch < channels_; }
  int channels_ = 0;
  bool active_low_ = true;
  uint8_t state_ = 0;
  ChangeCb change_cb_;
};

}  // namespace ha
// ===== src/logic/relay.cpp =====

namespace ha {

RelayBank::RelayBank() = default;

void RelayBank::configure(int channels, bool active_low) {
  if (channels < 0) channels = 0;
  if (channels > kMaxChannels) channels = kMaxChannels;
  channels_ = channels;
  active_low_ = active_low;
  state_ = 0;
}

bool RelayBank::set(int ch, bool on) {
  if (!valid(ch)) return false;
  bool prev = get(ch);
  if (on)
    state_ |= (uint8_t)(1u << ch);
  else
    state_ &= (uint8_t)(~(1u << ch));
  if (on != prev && change_cb_) change_cb_(ch, on);
  return true;
}

bool RelayBank::toggle(int ch) {
  if (!valid(ch)) return false;
  return set(ch, !get(ch));
}

bool RelayBank::get(int ch) const {
  if (!valid(ch)) return false;
  return (state_ & (1u << ch)) != 0;
}

int RelayBank::levelForChannel(int ch) const { return levelFor(get(ch)); }

}  // namespace ha
// ===== src/logic/debounce.h =====
// Debounced switch input with edge events and hold-repeat suppression.
// raw=true means "electrically pressed" (device layer inverts pull-ups).
#include <cstdint>

namespace ha {

class SwitchBank {
 public:
  enum Event { NONE, PRESSED, RELEASED };

  static const int kMaxChannels = 8;

  SwitchBank();

  // debounce_ms: settle time. hold_repeat_ms: 0 = suppress repeats while held.
  void configure(int channels, uint32_t debounce_ms, uint32_t hold_repeat_ms = 0);
  void reset();

  // Call every loop with the raw level and now (ms). Returns edge events.
  Event update(int ch, bool raw_pressed, uint32_t now_ms);

  bool pressed(int ch) const;  // stable (debounced) state

 private:
  bool valid(int ch) const { return ch >= 0 && ch < channels_; }
  int channels_ = 0;
  uint32_t debounce_ms_ = 50;
  uint32_t hold_repeat_ms_ = 0;
  bool stable_[kMaxChannels] = {false};
  bool candidate_[kMaxChannels] = {false};
  uint32_t candidate_since_[kMaxChannels] = {0};
  uint32_t last_press_at_[kMaxChannels] = {0};
};

}  // namespace ha
// ===== src/logic/debounce.cpp =====

namespace ha {

SwitchBank::SwitchBank() = default;

void SwitchBank::configure(int channels, uint32_t debounce_ms,
                           uint32_t hold_repeat_ms) {
  if (channels < 0) channels = 0;
  if (channels > kMaxChannels) channels = kMaxChannels;
  channels_ = channels;
  debounce_ms_ = debounce_ms;
  hold_repeat_ms_ = hold_repeat_ms;
  reset();
}

void SwitchBank::reset() {
  for (int i = 0; i < kMaxChannels; ++i) {
    stable_[i] = false;
    candidate_[i] = false;
    candidate_since_[i] = 0;
    last_press_at_[i] = 0;
  }
}

SwitchBank::Event SwitchBank::update(int ch, bool raw_pressed, uint32_t now_ms) {
  if (!valid(ch)) return NONE;
  if (raw_pressed != candidate_[ch]) {
    candidate_[ch] = raw_pressed;
    candidate_since_[ch] = now_ms;
    return NONE;
  }
  if (raw_pressed == stable_[ch]) return NONE;
  if ((uint32_t)(now_ms - candidate_since_[ch]) < debounce_ms_) return NONE;
  // Settled into a new stable state.
  stable_[ch] = raw_pressed;
  if (raw_pressed) {
    last_press_at_[ch] = now_ms;
    return PRESSED;
  }
  return RELEASED;
}

bool SwitchBank::pressed(int ch) const {
  if (!valid(ch)) return false;
  return stable_[ch];
}

}  // namespace ha
// ===== src/logic/logstore.h =====
// In-memory event log with age + size rotation.
// Storage format (one line per entry): "<epoch> <message>\n"
// Rendering (human timestamps) is injected so host tests stay libc-only.
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

namespace ha {

class LogStore {
 public:
  LogStore();

  void configure(size_t max_bytes, uint32_t max_age_days);
  size_t maxBytes() const { return max_bytes_; }

  void load(const std::string& content);  // parse existing file content
  void append(uint32_t epoch, const std::string& message);
  void prune(uint32_t now_epoch);  // drop entries older than max_age_days

  std::string dump() const;  // raw storage format (for writing to flash)
  size_t bytes() const;
  size_t entries() const { return entries_.size(); }

  // Human-readable lines, oldest first.
  using FormatFn = std::function<std::string(uint32_t epoch)>;
  std::vector<std::string> rendered(FormatFn fmt) const;

 private:
  struct Entry {
    uint32_t epoch;
    std::string message;
  };
  void enforceSize();
  size_t max_bytes_ = 65536;
  uint32_t max_age_days_ = 30;
  std::vector<Entry> entries_;
};

}  // namespace ha
// ===== src/logic/logstore.cpp =====

namespace ha {

LogStore::LogStore() = default;

void LogStore::configure(size_t max_bytes, uint32_t max_age_days) {
  max_bytes_ = max_bytes;
  max_age_days_ = max_age_days;
}

void LogStore::load(const std::string& content) {
  entries_.clear();
  size_t pos = 0;
  while (pos < content.size()) {
    size_t eol = content.find('\n', pos);
    std::string line = content.substr(pos, eol == std::string::npos
                                                 ? std::string::npos
                                                 : eol - pos);
    if (eol == std::string::npos)
      pos = content.size();
    else
      pos = eol + 1;
    if (line.empty()) continue;
    size_t sp = line.find(' ');
    if (sp == std::string::npos) continue;
    // No exceptions on embedded targets: validate digits manually.
    uint32_t epoch = 0;
    bool ok = sp > 0;
    for (size_t i = 0; ok && i < sp; i++) {
      char c = line[i];
      if (c < '0' || c > '9') {
        ok = false;
        break;
      }
      epoch = epoch * 10 + (uint32_t)(c - '0');
    }
    if (!ok) continue;
    entries_.push_back(Entry{epoch, line.substr(sp + 1)});
  }
  enforceSize();
}

void LogStore::append(uint32_t epoch, const std::string& message) {
  std::string clean = message;
  for (char& c : clean) {
    if (c == '\n' || c == '\r') c = ' ';
  }
  entries_.push_back(Entry{epoch, clean});
  enforceSize();
}

void LogStore::prune(uint32_t now_epoch) {
  if (max_age_days_ == 0) return;
  uint64_t cutoff = now_epoch > (uint64_t)max_age_days_ * 86400
                        ? now_epoch - (uint64_t)max_age_days_ * 86400
                        : 0;
  // Epoch 0 = "time unknown": keep those (better than deleting blindly).
  std::vector<Entry> kept;
  kept.reserve(entries_.size());
  for (const auto& e : entries_) {
    if (e.epoch == 0 || (uint64_t)e.epoch >= cutoff) kept.push_back(e);
  }
  entries_.swap(kept);
}

std::string LogStore::dump() const {
  std::string out;
  for (const auto& e : entries_) {
    out += std::to_string(e.epoch);
    out += ' ';
    out += e.message;
    out += '\n';
  }
  return out;
}

size_t LogStore::bytes() const { return dump().size(); }

std::vector<std::string> LogStore::rendered(FormatFn fmt) const {
  std::vector<std::string> lines;
  lines.reserve(entries_.size());
  for (const auto& e : entries_) lines.push_back(fmt(e.epoch) + " " + e.message);
  return lines;
}

void LogStore::enforceSize() {
  while (!entries_.empty() && bytes() > max_bytes_) {
    entries_.erase(entries_.begin());  // drop oldest first
  }
}

}  // namespace ha
// ===== src/logic/auth.h =====
// Credential store: salted SHA-256 hashes, admin forced-change on first boot,
// optional limited "user" account. No plaintext passwords anywhere.
#include <string>

namespace ha {

class AuthStore {
 public:
  AuthStore();

  // Salt should be device-unique (e.g. chip id hex). Tests use a fixed salt.
  void setSalt(const std::string& salt) { salt_ = salt; }

  bool adminConfigured() const { return !admin_hash_.empty(); }
  bool adminMustChange() const { return admin_must_change_; }
  void setAdminPassword(const std::string& password);  // clears must-change
  bool verifyAdmin(const std::string& password) const;

  void setUserEnabled(bool enabled);
  bool userEnabled() const { return user_enabled_; }
  void setUserPassword(const std::string& password);
  bool verifyUser(const std::string& password) const;

  // Persistable form: "admin_hash user_enabled user_hash must_change"
  std::string serialize() const;
  bool load(const std::string& data);

 private:
  static std::string hash(const std::string& salt, const std::string& password);
  std::string salt_ = "ha-default-salt";
  std::string admin_hash_;
  bool admin_must_change_ = true;
  bool user_enabled_ = false;
  std::string user_hash_;
};

}  // namespace ha
// ===== src/logic/auth.cpp =====

namespace ha {

AuthStore::AuthStore() = default;

std::string AuthStore::hash(const std::string& salt,
                            const std::string& password) {
  std::string in = salt + '\x00' + password;
  char hex[65];
  ha_sha256_hex(reinterpret_cast<const uint8_t*>(in.data()), in.size(), hex);
  return std::string(hex);
}

void AuthStore::setAdminPassword(const std::string& password) {
  admin_hash_ = hash(salt_, password);
  admin_must_change_ = false;
}

bool AuthStore::verifyAdmin(const std::string& password) const {
  if (admin_hash_.empty()) return false;
  return hash(salt_, password) == admin_hash_;
}

void AuthStore::setUserEnabled(bool enabled) { user_enabled_ = enabled; }

void AuthStore::setUserPassword(const std::string& password) {
  user_hash_ = hash(salt_, password);
}

bool AuthStore::verifyUser(const std::string& password) const {
  if (!user_enabled_ || user_hash_.empty()) return false;
  return hash(salt_, password) == user_hash_;
}

std::string AuthStore::serialize() const {
  return admin_hash_ + "\n" + (user_enabled_ ? "1" : "0") + "\n" + user_hash_ +
         "\n" + (admin_must_change_ ? "1" : "0") + "\n";
}

bool AuthStore::load(const std::string& data) {
  size_t p1 = data.find('\n');
  if (p1 == std::string::npos) return false;
  size_t p2 = data.find('\n', p1 + 1);
  if (p2 == std::string::npos) return false;
  size_t p3 = data.find('\n', p2 + 1);
  if (p3 == std::string::npos) return false;
  admin_hash_ = data.substr(0, p1);
  user_enabled_ = (data.substr(p1 + 1, p2 - p1 - 1) == "1");
  user_hash_ = data.substr(p2 + 1, p3 - p2 - 1);
  std::string mc = data.substr(p3 + 1);
  if (!mc.empty() && mc.back() == '\n') mc.pop_back();
  admin_must_change_ = (mc != "0");
  if (admin_hash_.size() != 64 && !admin_hash_.empty()) return false;
  return true;
}

}  // namespace ha
// ===== src/logic/ghota.h =====
// GitHub-release OTA helpers (hardware-independent, host-tested).
//
// Parses the (already downloaded) GitHub "latest release" JSON for the tag
// name and the first .bin asset URL, and compares dotted version numbers.
// The device layer only fetches bytes; all decisions live here.
#include <string>

namespace ha {
namespace ghota {

// Extract tag_name and first browser_download_url ending in ".bin".
// Returns true if at least the tag was found (bin URL may stay empty).
bool parseLatest(const std::string& json, std::string& tagOut,
                 std::string& binUrlOut);

// Compare dotted versions ("1.01" vs "1.0"): -1 / 0 / +1.
// Leading 'v'/'V' and surrounding whitespace are ignored; non-numeric
// suffixes ("-beta") make that component compare lower.
int compareVersions(const std::string& a, const std::string& b);

// True if `latest` is newer than `current`.
inline bool updateAvailable(const std::string& current,
                            const std::string& latest) {
  if (latest.empty()) return false;
  return compareVersions(latest, current) > 0;
}

}  // namespace ghota
}  // namespace ha
// ===== src/logic/ghota.cpp =====
#include <cctype>
#include <vector>

namespace ha {
namespace ghota {

namespace {
std::string trim(const std::string& s) {
  size_t a = 0;
  while (a < s.size() && isspace((unsigned char)s[a])) a++;
  size_t b = s.size();
  while (b > a && isspace((unsigned char)s[b - 1])) b--;
  std::string t = s.substr(a, b - a);
  if (!t.empty() && (t[0] == 'v' || t[0] == 'V')) t = t.substr(1);
  return t;
}

// Find "key" : "value" with optional whitespace. Returns false if absent.
bool jsonString(const std::string& json, const std::string& key,
                std::string& out, size_t from = 0) {
  std::string q = "\"" + key + "\"";
  size_t k = json.find(q, from);
  if (k == std::string::npos) return false;
  size_t c = json.find(':', k + q.size());
  if (c == std::string::npos) return false;
  size_t q1 = json.find('"', c + 1);
  if (q1 == std::string::npos) return false;
  size_t q2 = json.find('"', q1 + 1);
  if (q2 == std::string::npos) return false;
  out = json.substr(q1 + 1, q2 - q1 - 1);
  return true;
}
}  // namespace

bool parseLatest(const std::string& json, std::string& tagOut,
                 std::string& binUrlOut) {
  tagOut.clear();
  binUrlOut.clear();
  if (!jsonString(json, "tag_name", tagOut)) return false;
  // First asset whose download URL ends in .bin (query strings stripped).
  size_t from = 0;
  std::string url;
  while (jsonString(json, "browser_download_url", url, from)) {
    size_t end = url.find_first_of("?#");
    std::string path = url.substr(0, end);
    if (path.size() >= 4 &&
        path.compare(path.size() - 4, 4, ".bin") == 0) {
      binUrlOut = url;
      break;
    }
    from = json.find(url, from) + url.size();
    if (from == std::string::npos) break;
  }
  return true;
}

int compareVersions(const std::string& a, const std::string& b) {
  std::string ta = trim(a), tb = trim(b);
  size_t ia = 0, ib = 0;
  while (ia < ta.size() || ib < tb.size()) {
    // Parse one numeric component from each side.
    long na = 0, nb = 0;
    bool aPre = false, bPre = false;
    while (ia < ta.size() && ta[ia] != '.') {
      char c = ta[ia++];
      if (isdigit((unsigned char)c))
        na = na * 10 + (c - '0');
      else if (c == '-' || !(na == 0 && (c == ' ')))
        aPre = true;  // pre-release suffix devalues the component
    }
    while (ib < tb.size() && tb[ib] != '.') {
      char c = tb[ib++];
      if (isdigit((unsigned char)c))
        nb = nb * 10 + (c - '0');
      else
        bPre = true;
    }
    if (ia < ta.size() && ta[ia] == '.') ia++;
    if (ib < tb.size() && tb[ib] == '.') ib++;
    if (na != nb) return na < nb ? -1 : 1;
    if (aPre != bPre) return aPre ? -1 : 1;  // release beats pre-release
  }
  return 0;
}

}  // namespace ghota
}  // namespace ha
// ===== src/logic/resetwin.h =====
// Multi-reset recovery counter ("press RESET 3 times").
// Counts consecutive boots inside a time window; the count itself is persisted
// by the device layer (ESP8266 RTC memory survives resets, not power loss).
// Pure logic so host tests can drive it.

namespace ha {

class ResetWindow {
 public:
  ResetWindow();

  void configure(int threshold, unsigned long window_ms);
  void loadCount(int n) { count_ = n < 0 ? 0 : n; }
  int count() const { return count_; }

  // Call once per boot. Returns true when the threshold is reached.
  bool noteBoot() {
    count_++;
    return count_ >= threshold_;
  }

  void clear() { count_ = 0; }

 private:
  int threshold_ = 3;
  unsigned long window_ms_ = 20000;
  int count_ = 0;
};

inline ResetWindow::ResetWindow() = default;

inline void ResetWindow::configure(int threshold, unsigned long window_ms) {
  if (threshold < 2) threshold = 2;
  threshold_ = threshold;
  window_ms_ = window_ms;
  count_ = 0;
}

}  // namespace ha
// ===== src/logic/scheduler.h =====
// Rollover-safe periodic timer (unsigned subtraction handles millis() wrap).
#include <cstdint>

namespace ha {

class Every {
 public:
  explicit Every(uint32_t interval_ms = 1000) : interval_(interval_ms) {}
  void setInterval(uint32_t ms) { interval_ = ms; }
  void reset(uint32_t now_ms) { last_ = now_ms; armed_ = true; }
  // True once per interval. First call after construction fires immediately.
  bool due(uint32_t now_ms) {
    if (!armed_) {
      armed_ = true;
      last_ = now_ms;
      return true;
    }
    if ((uint32_t)(now_ms - last_) >= interval_) {
      last_ = now_ms;
      return true;
    }
    return false;
  }

 private:
  uint32_t interval_;
  uint32_t last_ = 0;
  bool armed_ = false;
};

}  // namespace ha
// ===== src/config.h =====
// Hardware + behavior configuration for v1.0.
//
// PIN MAP (generic ESP8266 dev module / ESP-12E / NodeMCU):
//   Relays  D1 D2 D6 D7 = GPIO 5,4,12,13  (no strapping, no UART, no flash bus)
//   Switches D5 D0 + FLASH btn + D4 LED   = GPIO 14,16,0,2 (buttons to GND)
// Avoided: GPIO1(TX) 3(RX) 6-11(flash) 15(strapping).
// GPIO16 has NO internal pull-up: fit an external 10 kΩ resistor to 3V3.
// GPIO0/2 use INPUT_PULLUP + button-to-GND (same as the FLASH button: safe).

#define HA_CHANNELS 4

#define HA_VERSION "1.01"

// Triple-reset recovery: this many RESET presses inside the window below
// wipes WiFi credentials and opens the config portal.
#define HA_RESET_COUNT 3
#define HA_RESET_WINDOW_MS 20000UL

// Re-attempt WiFi association after this long without a connection.
#define HA_RECONNECT_AFTER_MS 60000UL

#define HA_RELAY_PINS \
  { 5, 4, 12, 13 }
#define HA_SWITCH_PINS \
  { 14, 16, 0, 2 }

#ifndef RELAY_ACTIVE_LOW
#define RELAY_ACTIVE_LOW 1  // common relay modules trigger on LOW
#endif

#define HA_DEBOUNCE_MS 50
#define HA_PORTAL_TRIGGER_HOLD_MS 8000  // hold switch 1 to open WiFi portal
#define HA_PORTAL_TIMEOUT_S 300
#define HA_NTP_SERVER "in.pool.ntp.org"
#define HA_NTP_OFFSET_S 19800  // Asia/Kolkata +5:30
#define HA_NTP_INTERVAL_MS 300000UL
#define HA_LOG_FILE "/log.txt"
#define HA_LOG_MAX_BYTES 65536
#define HA_LOG_MAX_AGE_DAYS 30
#define HA_AUTH_FILE "/auth.dat"
#define HA_RELAY_FILE "/relays.dat"
#define HA_OTAKEY_FILE "/otakey.txt"
#define HA_KEEPALIVE_INTERVAL_MS 900000UL  // 15 min anti-idle probe
#define HA_LOG_FLUSH_INTERVAL_MS 60000UL
#define HA_LOG_FLUSH_EVERY_N 25
// ===== src/device/app_context.h =====
// Shared application context passed to device modules.
#include <functional>
#include <string>

struct AppContext {
  ha::RelayBank* relays = nullptr;
  ha::SwitchBank* switches = nullptr;
  ha::LogStore* log = nullptr;
  ha::AuthStore* auth = nullptr;

  const int* relayPins = nullptr;
  const int* switchPins = nullptr;
  int channels = 0;

  // Time / status supplied by main.cpp.
  std::function<uint32_t()> epochNow;
  std::function<std::string(uint32_t)> fmtTime;
  std::function<void(const std::string&)> addLog;  // append + schedule flush
  std::function<void()> saveAll;                   // persist relays/auth/log
  std::function<void()> requestPortal;             // open WiFi portal ASAP
  std::function<void()> requestReboot;

  bool* wifiUp = nullptr;
  bool* ntpOk = nullptr;
  std::string* otaPassword = nullptr;  // ArduinoOTA/HTTP-upload password
  const char* fwVersion = nullptr;     // HA_VERSION, shown on /update
};
// ===== src/device/fs_store.h =====
// LittleFS persistence helpers (device only).
#include <string>

bool fsBegin(bool formatOnFail = true);
std::string fsReadFile(const char* path);
bool fsWriteFile(const char* path, const std::string& data);
// ===== src/device/fs_store.cpp =====
#include <LittleFS.h>

bool fsBegin(bool formatOnFail) {
  if (LittleFS.begin()) return true;
  if (!formatOnFail) return false;
  LittleFS.format();
  return LittleFS.begin();
}

std::string fsReadFile(const char* path) {
  File f = LittleFS.open(path, "r");
  if (!f) return std::string();
  std::string out;
  out.reserve(f.size());
  while (f.available()) out += (char)f.read();
  f.close();
  return out;
}

bool fsWriteFile(const char* path, const std::string& data) {
  File f = LittleFS.open(path, "w");
  if (!f) return false;
  size_t n = f.write((const uint8_t*)data.data(), data.size());
  f.close();
  return n == data.size();
}
// ===== src/device/reset_recovery.h =====
// Triple-reset recovery backed by ESP8266 RTC user memory.
//
// Concept: khoih-prog's ESP_DoubleResetDetector (count boots inside a window).
// Mechanism: ESP8266 Arduino core `ESP.rtcUserMemoryRead/Write` — RTC memory
// survives resets (incl. the RESET button and ESP.restart) but NOT power loss,
// which is exactly the semantics a "press reset N times" detector needs.
// Uses words 64..66, clear of the SDK-reserved low region.
//
// Rule: call resetRecoveryBoot() early in setup(). Before ANY intentional
// ESP.restart(), call resetRecoveryDisarm() so self-reboots are never
// mistaken for button presses.

// Returns the persisted consecutive-boot count (0 on power-up/first boot).
int resetRecoveryCount();
// Persist a count (device mirrors ha::ResetWindow here).
void resetRecoverySave(int count);
// Clear the count: call after the window expires (uptime) or after recovery.
void resetRecoveryClear();
// Mark the next reboot as intentional (not a button press).
void resetRecoveryDisarm();
// ===== src/device/reset_recovery.cpp =====
#include <ESP8266WiFi.h>

static const uint32_t kMagic = 0x48415243;  // "HARC"
static const uint32_t kRtcOffset = 64;      // words; above SDK-reserved area

struct RtcSlot {
  uint32_t magic;
  uint32_t count;
  uint32_t spare;
};

static bool rtcRead(RtcSlot& s) {
  if (!ESP.rtcUserMemoryRead(kRtcOffset, (uint32_t*)&s, sizeof(s) / 4))
    return false;
  return s.magic == kMagic;
}

static void rtcWrite(const RtcSlot& s) {
  ESP.rtcUserMemoryWrite(kRtcOffset, (uint32_t*)&s, sizeof(s) / 4);
}

int resetRecoveryCount() {
  RtcSlot s{0, 0, 0};
  if (!rtcRead(s)) return 0;
  return (int)s.count;
}

void resetRecoverySave(int count) {
  RtcSlot s{kMagic, (uint32_t)(count < 0 ? 0 : count), 0};
  rtcWrite(s);
}

void resetRecoveryClear() {
  RtcSlot s{0, 0, 0};  // bad magic == "no history"
  rtcWrite(s);
}

void resetRecoveryDisarm() { resetRecoveryClear(); }
// ===== src/device/time_sync.h =====
// NTP time sync (device only). TimeLib holds wall-clock for formatting.
#include <cstdint>
#include <string>

void timeSyncBegin();
bool timeSyncForceUpdate(int retries = 5);  // blocking, call at boot
void timeSyncLoop();                        // call every loop
uint32_t timeEpoch();                       // 0 = unknown
bool timeIsValid();
std::string timeFormat(uint32_t epoch);  // "[YYYY-MM-DD HH:MM:SS]", 24B-safe
// ===== src/device/time_sync.cpp =====
#include <ESP8266WiFi.h>
#include <NTPClient.h>
#include <TimeLib.h>
#include <WiFiUdp.h>

static WiFiUDP s_udp;
static NTPClient s_ntp(s_udp, HA_NTP_SERVER, HA_NTP_OFFSET_S, HA_NTP_INTERVAL_MS);
static bool s_valid = false;

void timeSyncBegin() {
  s_ntp.begin();
}

bool timeSyncForceUpdate(int retries) {
  for (int i = 0; i < retries; i++) {
    if (s_ntp.forceUpdate()) {
      setTime(s_ntp.getEpochTime());
      s_valid = true;
      return true;
    }
    delay(500);
  }
  return false;
}

void timeSyncLoop() {
  if (WiFi.status() != WL_CONNECTED) return;
  if (s_ntp.update()) {
    setTime(s_ntp.getEpochTime());
    s_valid = true;
  }
}

uint32_t timeEpoch() { return s_valid ? (uint32_t)s_ntp.getEpochTime() : 0; }
bool timeIsValid() { return s_valid; }

std::string timeFormat(uint32_t epoch) {
  char buf[24];
  if (epoch == 0) {
    snprintf(buf, sizeof(buf), "[no-time]");
    return std::string(buf);
  }
  // Break down without touching the global TimeLib clock.
  uint32_t days = epoch / 86400UL;
  uint32_t secs = epoch % 86400UL;
  // Civil-from-days (Howard Hinnant algorithm), days since 1970-01-01.
  int64_t z = (int64_t)days + 719468;
  int64_t era = (z >= 0 ? z : z - 146096) / 146097;
  uint64_t doe = (uint64_t)(z - era * 146097);
  uint64_t yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
  int64_t y = (int64_t)yoe + era * 400;
  uint64_t doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
  uint64_t mp = (5 * doy + 2) / 153;
  uint64_t d = doy - (153 * mp + 2) / 5 + 1;
  uint64_t m = mp + (mp < 10 ? 3 : -9);
  y += (m <= 2);
  snprintf(buf, sizeof(buf), "[%04d-%02d-%02d %02d:%02d:%02d]", (int)y, (int)m,
           (int)d, (int)(secs / 3600), (int)((secs % 3600) / 60),
           (int)(secs % 60));
  return std::string(buf);
}
// ===== src/device/wifi_portal.h =====
// WiFi connection via WiFiManager captive portal (device only).
#include <string>

// Blocking connect with portal fallback (call at boot).
// Returns true if STA connected. Portal SSID gets a chip-id suffix.
bool wifiPortalBoot(const char* baseApName = "ESP-Setup",
                    int portalTimeoutS = 300);

// Non-blocking check; call every few seconds to update status.
void wifiPortalPoll();

// Open the config portal on demand (long-press / web button).
void wifiPortalOpen(const char* baseApName = "ESP-Setup",
                    int portalTimeoutS = 300);

bool wifiIsUp();
std::string wifiIp();
std::string wifiApName(const char* base);
// ===== src/device/wifi_portal.cpp =====
#include <ESP8266WiFi.h>
#include <WiFiManager.h>

static bool s_up = false;

std::string wifiApName(const char* base) {
  uint32_t id = ESP.getChipId();
  char name[32];
  snprintf(name, sizeof(name), "%s-%04X", base, (unsigned)(id & 0xFFFF));
  return std::string(name);
}

bool wifiPortalBoot(const char* baseApName, int portalTimeoutS) {
  WiFi.mode(WIFI_STA);
  WiFiManager wm;
  wm.setTitle("ESP Home Setup");
  wm.setConfigPortalTimeout(portalTimeoutS);
  wm.setConnectTimeout(20);
  std::string ap = wifiApName(baseApName);
  s_up = wm.autoConnect(ap.c_str());
  return s_up;
}

void wifiPortalPoll() { s_up = (WiFi.status() == WL_CONNECTED); }

void wifiPortalOpen(const char* baseApName, int portalTimeoutS) {
  WiFiManager wm;
  wm.setTitle("ESP Home Setup");
  wm.setConfigPortalTimeout(portalTimeoutS);
  std::string ap = wifiApName(baseApName);
  wm.startConfigPortal(ap.c_str());
  wifiPortalPoll();
}

bool wifiIsUp() { return s_up; }

std::string wifiIp() {
  if (!s_up) return std::string("0.0.0.0");
  return std::string(WiFi.localIP().toString().c_str());
}
// ===== src/device/gh_update.h =====
// GitHub-release OTA: "press Update, get the latest GitHub release".
//
// Flow: HTTPS GET api.github.com → ha::ghota::parseLatest finds tag + .bin
// asset → HTTPS download (follows github.com → objects.* redirect) →
// flash via the Updater class (same engine as the Arduino OTA core).
// TLS: BearSSL with setInsecure() — see SOURCES.md; acceptable on a trusted
// LAN because the flashed image is only accepted if the Update checksum
// closes cleanly, and releases come from the owner's repo. (ESP8266 Arduino
// core BearSSL docs; GitHub REST "Get the latest release" API.)
#include <string>

#define HA_GH_OWNER "bm-a"
#define HA_GH_REPO "ESP8266-Home-Automation"

// Fetch latest tag + .bin URL. Empty tag = check failed (offline/API error).
// Logs nothing; caller decides. `bodyOut` receives raw JSON when non-null.
bool ghCheckLatest(std::string& tagOut, std::string& binUrlOut,
                   std::string* bodyOut = nullptr);

// Download `binUrl` and flash it. Returns true on verified success.
// Caller MUST reboot afterwards. Progress goes to `logFn` (may be null).
bool ghDownloadAndFlash(const std::string& binUrl,
                        void (*logFn)(const std::string&) = nullptr);
// ===== src/device/gh_update.cpp =====
#include <ESP8266HTTPClient.h>
#include <Updater.h>
#include <WiFiClientSecure.h>

static const char* kApiHost = "api.github.com";
static const int kApiPort = 443;

static void applySecure(WiFiClientSecure& c) {
  c.setInsecure();
  c.setTimeout(15000);
}

bool ghCheckLatest(std::string& tagOut, std::string& binUrlOut,
                   std::string* bodyOut) {
  tagOut.clear();
  binUrlOut.clear();
  WiFiClientSecure client;
  applySecure(client);
  HTTPClient http;
  std::string path = std::string("/repos/") + HA_GH_OWNER + "/" + HA_GH_REPO +
                     "/releases/latest";
  if (!http.begin(client, kApiHost, kApiPort, path.c_str(), true)) return false;
  http.setUserAgent("esp-home-ota");
  http.setTimeout(15000);
  http.addHeader("Accept", "application/vnd.github+json");
  int code = http.GET();
  if (code != HTTP_CODE_OK) {
    http.end();
    return false;
  }
  String body = http.getString();
  http.end();
  std::string raw(body.c_str(), body.length());
  if (bodyOut) *bodyOut = raw;
  return ha::ghota::parseLatest(raw, tagOut, binUrlOut);
}

bool ghDownloadAndFlash(const std::string& binUrl,
                        void (*logFn)(const std::string&)) {
  if (binUrl.empty()) return false;
  WiFiClientSecure client;
  applySecure(client);
  HTTPClient http;
  http.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
  http.setUserAgent("esp-home-ota");
  http.setTimeout(20000);
  if (!http.begin(client, binUrl.c_str())) return false;
  int code = http.GET();
  if (code != HTTP_CODE_OK) {
    http.end();
    return false;
  }
  int total = http.getSize();
  if (total <= 0) {
    http.end();
    return false;
  }
  uint32_t maxSketch = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
  if (!Update.begin(maxSketch)) {
    http.end();
    return false;
  }
  size_t written = Update.writeStream(http.getStream());
  bool ok = (written == (size_t)total) && Update.end(true);
  if (logFn) {
    char msg[96];
    snprintf(msg, sizeof(msg), "GitHub OTA %s (%u bytes)",
             ok ? "applied" : "FAILED", (unsigned)written);
    logFn(msg);
  }
  http.end();
  return ok && !Update.hasError();
}
// ===== src/device/ota_service.h =====
// OTA: ArduinoOTA (IDE uploads) + authenticated HTTP upload (device only).
#include <string>

void otaBegin(const std::string& hostname, const std::string& password);
void otaLoop();
// Apply a new password (takes effect after reboot).
void otaSetPassword(const std::string& password);
// ===== src/device/ota_service.cpp =====
#include <ArduinoOTA.h>

static std::string s_pending_password;

void otaBegin(const std::string& hostname, const std::string& password) {
  ArduinoOTA.setHostname(hostname.c_str());
  if (!password.empty()) ArduinoOTA.setPassword(password.c_str());
  ArduinoOTA.onStart([]() {});
  ArduinoOTA.onError([](ota_error_t) {});
  ArduinoOTA.begin();
}

void otaLoop() { ArduinoOTA.handle(); }

void otaSetPassword(const std::string& password) {
  s_pending_password = password;  // applied on next boot by main.cpp
  (void)s_pending_password;
}
// ===== src/device/web_ui.h =====
// Web UI + JSON API (device only).

void webBegin(AppContext* ctx);
void webLoop();
// ===== src/device/web_ui.cpp =====
#include <ESP8266WebServer.h>
#include <Updater.h>
#include <Uri.h>

static ESP8266WebServer s_server(80);
static AppContext* s_web = nullptr;
static bool s_uploadAllowed = false;

// Roles as plain ints: Arduino IDE hoists prototypes above enum definitions,
// so a custom enum type in signatures breaks the single-file sketch build.
static const int R_NONE = 0;
static const int R_USER = 1;
static const int R_ADMIN = 2;

// --- tiny base64 decoder (for "Basic <b64>") ---
static int b64val(char c) {
  if (c >= 'A' && c <= 'Z') return c - 'A';
  if (c >= 'a' && c <= 'z') return c - 'a' + 26;
  if (c >= '0' && c <= '9') return c - '0' + 52;
  if (c == '+') return 62;
  if (c == '/') return 63;
  return -1;
}
static std::string b64decode(const String& in) {
  std::string out;
  int val = 0, bits = 0;
  for (size_t i = 0; i < in.length(); i++) {
    char c = in[i];
    if (c == '=') break;
    int v = b64val(c);
    if (v < 0) continue;
    val = (val << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out += (char)((val >> bits) & 0xFF);
    }
  }
  return out;
}

static int currentRole() {
  String h = s_server.header("Authorization");
  if (!h.startsWith("Basic ")) return R_NONE;
  std::string cred = b64decode(h.substring(6));
  size_t pos = cred.find(':');
  if (pos == std::string::npos) return R_NONE;
  std::string user = cred.substr(0, pos);
  std::string pass = cred.substr(pos + 1);
  if (user == "admin" && s_web->auth->verifyAdmin(pass)) return R_ADMIN;
  if (user == "user" && s_web->auth->verifyUser(pass)) return R_USER;
  return R_NONE;
}

static bool needAuth(int minimum) {
  int r = currentRole();
  if (r >= minimum && r != R_NONE) return false;
  s_server.requestAuthentication();
  return true;
}

// First-boot gate: force admin password setup before anything else.
static bool setupGate() {
  if (!s_web->auth->adminMustChange()) return false;
  String uri = s_server.uri();
  if (uri == "/setup" || uri == "/api/setup" || uri == "/api/state")
    return false;
  s_server.sendHeader("Location", "/setup");
  s_server.send(302, "text/plain", "Setup required");
  return true;
}

static const char* kCss =
    "body{background:#000;color:#fff;font-family:'Courier New',monospace;"
    "margin:0}main{max-width:720px;margin:0 auto;padding:20px}"
    "h1{font-size:22px;border-bottom:2px solid #2ecc40;padding-bottom:6px}"
    "button{background:#2ecc40;color:#000;border:0;padding:10px 22px;font-size:16px;"
    "cursor:pointer;margin:4px;font-family:inherit}"
    "button.off{background:#555;color:#fff}"
    "input{background:#111;color:#fff;border:1px solid #2ecc40;padding:8px;margin:4px;"
    "font-family:inherit}label{display:block;margin-top:8px}"
    ".card{border:1px solid #2ecc40;padding:12px;margin:12px 0}"
    ".log{border:1px solid #fff;padding:10px;max-height:300px;overflow-y:auto;"
    "font-size:13px}.row{display:flex;align-items:center;gap:8px;margin:6px 0}"
    "nav a{color:#2ecc40;margin-right:14px}";

static void page(const String& title, const String& body) {
  String html = "<html><head><meta name='viewport' content='width=device-width'>"
                "<title>" +
                title + "</title><style>" + kCss +
                "</style></head><body><main><nav><a href='/'>Home</a>"
                "<a href='/logs'>Logs</a><a href='/settings'>Settings</a>"
                "<a href='/update'>OTA</a></nav><h1>" +
                title + "</h1>" + body + "</main></body></html>";
  s_server.send(200, "text/html", html);
}

static void handleRoot() {
  if (setupGate()) return;
  if (needAuth(R_USER)) return;
  String body =
      "<div class='card'><div id='st'>loading…</div></div>"
      "<div class='card' id='relays'></div>"
      "<script>"
      "async function st(){const r=await fetch('/api/state');const j=await r.json();"
      "document.getElementById('st').innerHTML='Time '+j.time+' | IP '+j.ip+' | RSSI '+j.rssi+' dBm';"
      "let h='';j.relays.forEach((s,i)=>{h+='<div class=row><b>Relay '+(i+1)+'</b> '+(s?'ON':'OFF')+"
      "' <button '+(s?'':'class=off')+' onclick=\"setR('+i+','+(s?'0':'1')+')\">'+(s?'Turn OFF':'Turn ON')+'</button></div>'});"
      "document.getElementById('relays').innerHTML=h;}"
      "async function setR(i,on){await fetch('/api/relay',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'ch='+i+'&on='+on});st();}"
      "st();setInterval(st,2000);</script>";
  page("ESP Home", body);
}

static void handleSetup() {
  if (!s_web->auth->adminMustChange()) {
    s_server.sendHeader("Location", "/");
    s_server.send(302, "text/plain", "Already set up");
    return;
  }
  String body =
      "<div class='card'><p>First boot: set the admin password to unlock the "
      "device. (Default credentials are intentionally absent.)</p>"
      "<label>Admin password (min 8 chars)<input type='password' id='pw'></label>"
      "<button onclick=\"f()\">Save &amp; unlock</button><p id='m'></p></div>"
      "<script>async function f(){const pw=document.getElementById('pw').value;"
      "const r=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'password='+encodeURIComponent(pw)});"
      "document.getElementById('m').innerText=await r.text();if(r.ok)location='/';}</script>";
  page("First-time setup", body);
}

static void handleApiSetup() {
  if (!s_web->auth->adminMustChange()) {
    s_server.send(403, "text/plain", "Already set up");
    return;
  }
  String pw = s_server.arg("password");
  if (pw.length() < 8) {
    s_server.send(400, "text/plain", "Password must be >= 8 characters");
    return;
  }
  s_web->auth->setAdminPassword(pw.c_str());
  if (s_web->otaPassword->empty()) *s_web->otaPassword = pw.c_str();
  s_web->saveAll();
  s_web->addLog("Admin password set (first boot)");
  s_server.send(200, "text/plain", "OK - now log in as admin");
}

static String stateJson() {
  String j = "{";
  j += "\"time\":\"" + String(s_web->fmtTime(s_web->epochNow()).c_str()) + "\",";
  j += "\"ip\":\"" + String(wifiIp().c_str()) + "\",";
  j += "\"rssi\":" + String(WiFi.RSSI()) + ",";
  j += "\"ntp\":" + String(*s_web->ntpOk ? "true" : "false") + ",";
  j += "\"uptime\":" + String(millis() / 1000) + ",";
  j += "\"relays\":[";
  for (int i = 0; i < s_web->channels; i++) {
    if (i) j += ",";
    j += s_web->relays->get(i) ? "true" : "false";
  }
  j += "]}";
  return j;
}

static void handleApiState() {
  if (setupGate()) return;
  if (needAuth(R_USER)) return;
  s_server.send(200, "application/json", stateJson());
}

static void applyRelay(int ch, bool on, const char* src) {
  if (!s_web->relays->set(ch, on)) {
    s_server.send(400, "text/plain", "Invalid channel");
    return;
  }
  digitalWrite(s_web->relayPins[ch], s_web->relays->levelForChannel(ch));
  char msg[64];
  snprintf(msg, sizeof(msg), "Relay %d %s (%s)", ch + 1, on ? "ON" : "OFF", src);
  s_web->addLog(msg);
  s_server.send(200, "application/json",
                "{\"ch\":" + String(ch) + ",\"on\":" + (on ? "true" : "false") + "}");
}

static void handleApiRelay() {
  if (setupGate()) return;
  if (needAuth(R_USER)) return;
  int ch = s_server.arg("ch").toInt();
  if (s_server.hasArg("on"))
    applyRelay(ch, s_server.arg("on") == "1", "web");
  else
    applyRelay(ch, !s_web->relays->get(ch), "web");  // toggle
}

static void handleRelayToggleLegacy(int i) {
  // POST /relay/<i> — v3-compatible shape, now actually routed.
  if (setupGate()) return;
  if (needAuth(R_USER)) return;
  if (i < 0 || i >= s_web->channels) {
    s_server.send(400, "text/plain", "Invalid relay index");
    return;
  }
  applyRelay(i, !s_web->relays->get(i), "web");
}

static void handleLogs() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  String body = "<div class='log' id='l'>loading…</div><script>"
                "fetch('/api/logs').then(r=>r.text()).then(t=>{"
                "document.getElementById('l').innerText=t;});</script>";
  page("Event log", body);
}

static void handleApiLogs() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  auto lines = s_web->log->rendered(
      [](uint32_t e) { return s_web->fmtTime(e); });
  String out;
  for (auto& l : lines) {
    out += String(l.c_str());
    out += "\n";
  }
  s_server.send(200, "text/plain", out);
}

static void handleSettings() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  String body =
      "<div class='card'><h3>Admin password</h3>"
      "<input type='password' id='ap' placeholder='new admin password'>"
      "<button onclick=\"p('/api/adminpw',{password:document.getElementById('ap').value})\">Change</button></div>"
      "<div class='card'><h3>User account (limited: relays only)</h3>"
      "<label><input type='checkbox' id='ue'> enabled</label>"
      "<input type='password' id='up' placeholder='user password'>"
      "<button onclick=\"p('/api/userset',{enabled:document.getElementById('ue').checked?1:0,password:document.getElementById('up').value})\">Save</button></div>"
      "<div class='card'><h3>OTA password (Arduino IDE + HTTP upload)</h3>"
      "<input type='password' id='op' placeholder='ota password'>"
      "<button onclick=\"p('/api/otapw',{password:document.getElementById('op').value})\">Change</button></div>"
      "<div class='card'><h3>Device</h3>"
      "<button onclick=\"p('/api/portal',{})\">Open WiFi portal</button> "
      "<button onclick=\"if(confirm('Reboot?'))p('/api/restart',{})\">Reboot</button></div>"
      "<p id='m'></p>"
      "<script>async function p(u,b){const f=new URLSearchParams(b);"
      "const r=await fetch(u,{method:'POST',body:f});"
      "document.getElementById('m').innerText=await r.text();}</script>";
  page("Settings", body);
}

static void handleAdminPw() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  String pw = s_server.arg("password");
  if (pw.length() < 8) {
    s_server.send(400, "text/plain", "Min 8 characters");
    return;
  }
  s_web->auth->setAdminPassword(pw.c_str());
  s_web->saveAll();
  s_web->addLog("Admin password changed");
  s_server.send(200, "text/plain", "Admin password changed");
}

static void handleUserSet() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  bool en = s_server.arg("enabled") == "1";
  String pw = s_server.arg("password");
  if (en && pw.length() < 4) {
    s_server.send(400, "text/plain", "User password min 4 characters");
    return;
  }
  s_web->auth->setUserEnabled(en);
  if (pw.length()) s_web->auth->setUserPassword(pw.c_str());
  s_web->saveAll();
  s_web->addLog(en ? "User account enabled" : "User account disabled");
  s_server.send(200, "text/plain", "User settings saved");
}

static void handleOtaPw() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  String pw = s_server.arg("password");
  if (pw.length() < 8) {
    s_server.send(400, "text/plain", "Min 8 characters");
    return;
  }
  *s_web->otaPassword = pw.c_str();
  s_web->saveAll();
  s_web->addLog("OTA password changed (applies after reboot)");
  s_server.send(200, "text/plain", "OTA password saved - reboot to apply");
}

static void handlePortal() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  s_server.send(200, "text/plain", "Opening portal…");
  delay(500);
  s_web->requestPortal();
}

static void handleRestart() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  s_server.send(200, "text/plain", "Rebooting…");
  delay(500);
  s_web->requestReboot();
}

static void handleUpdatePage() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  String body =
      "<div class='card'><h3>Automatic update (GitHub release)</h3>"
      "<p>Running: <b>" +
      String(s_web->fwVersion) +
      "</b> <span id='g'>…checking…</span></p>"
      "<button onclick='ghcheck()'>Check for updates</button> "
      "<span id='gi'></span><p id='gm'></p></div>"
      "<div class='card'><h3>Manual upload</h3><p>Upload a compiled .bin. "
      "Device reboots automatically.</p>"
      "<form method='POST' action='/update' enctype='multipart/form-data'>"
      "<input type='file' name='firmware'><button type='submit'>Upload</button>"
      "</form></div>"
      "<script>async function ghcheck(){document.getElementById('g').innerText='checking…';"
      "const r=await fetch('/api/ghcheck');const j=await r.json();"
      "document.getElementById('g').innerText='latest: '+(j.tag||'check failed');"
      "document.getElementById('gi').innerHTML=j.newer?'<button onclick=\"ghup(\\''+j.url+'\\')\">Install '+j.tag+'</button>':'';}"
      "async function ghup(u){if(!confirm('Flash '+u+'?'))return;"
      "document.getElementById('gm').innerText='downloading… (up to a minute)';"
      "const f=new URLSearchParams({url:u});"
      "const r=await fetch('/api/ghupdate',{method:'POST',body:f});"
      "document.getElementById('gm').innerText=await r.text();}"
      "ghcheck();</script>";
  page("Firmware update", body);
}

static void handleUpdateUpload() {
  HTTPUpload& up = s_server.upload();
  if (up.status == UPLOAD_FILE_START) {
    s_uploadAllowed = (currentRole() == R_ADMIN);
    if (s_uploadAllowed) {
      uint32_t maxSketch = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
      Update.begin(maxSketch);
    }
  } else if (up.status == UPLOAD_FILE_WRITE) {
    if (s_uploadAllowed) Update.write(up.buf, up.currentSize);
  } else if (up.status == UPLOAD_FILE_END) {
    if (s_uploadAllowed && Update.end(true))
      s_web->addLog("OTA update applied via HTTP");
    else if (s_uploadAllowed)
      s_web->addLog("OTA update FAILED");
  }
}

static void handleUpdateDone() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  if (!s_uploadAllowed || Update.hasError()) {
    s_server.send(403, "text/plain", "Update failed or not authorized");
    return;
  }
  s_server.send(200, "text/plain", "Update OK - rebooting…");
  delay(500);
  s_web->requestReboot();  // via main: persists + disarms reset detector
}

static void handleApiGhCheck() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  std::string tag, url;
  bool ok = ghCheckLatest(tag, url);
  String j = "{\"ok\":";
  j += ok ? "true" : "false";
  j += ",\"current\":\"" + String(s_web->fwVersion) + "\"";
  j += ",\"tag\":\"" + String(tag.c_str()) + "\"";
  j += ",\"url\":\"" + String(url.c_str()) + "\"";
  j += ",\"newer\":";
  j += (ok && ha::ghota::updateAvailable(s_web->fwVersion, tag)) ? "true"
                                                                 : "false";
  j += "}";
  s_server.send(200, "application/json", j);
}

static void handleApiGhUpdate() {
  if (setupGate()) return;
  if (needAuth(R_ADMIN)) return;
  std::string url = s_server.arg("url").c_str();
  if (url.empty()) {
    s_server.send(400, "text/plain", "Missing url");
    return;
  }
  auto logFn = [](const std::string& m) { s_web->addLog(m); };
  s_server.sendHeader("Connection", "close");
  if (!ghDownloadAndFlash(url, logFn)) {
    s_server.send(500, "text/plain", "Download/flash failed - see log");
    return;
  }
  s_server.send(200, "text/plain", "Update OK - rebooting…");
  delay(500);
  s_web->requestReboot();
}

static void handleNotFound() {
  // Legacy relay path with manual parse (core 3.1.x has no UriBraces).
  String uri = s_server.uri();
  if (s_server.method() == HTTP_POST && uri.startsWith("/relay/")) {
    handleRelayToggleLegacy(uri.substring(7).toInt());
    return;
  }
  s_server.send(404, "text/plain", "Not found");
}

void webBegin(AppContext* ctx) {
  s_web = ctx;
  s_server.collectHeaders("Authorization");
  s_server.on("/", HTTP_GET, handleRoot);
  s_server.on("/setup", HTTP_GET, handleSetup);
  s_server.on("/api/setup", HTTP_POST, handleApiSetup);
  s_server.on("/api/state", HTTP_GET, handleApiState);
  s_server.on("/api/relay", HTTP_POST, handleApiRelay);
  s_server.on("/logs", HTTP_GET, handleLogs);
  s_server.on("/api/logs", HTTP_GET, handleApiLogs);
  s_server.on("/settings", HTTP_GET, handleSettings);
  s_server.on("/api/adminpw", HTTP_POST, handleAdminPw);
  s_server.on("/api/userset", HTTP_POST, handleUserSet);
  s_server.on("/api/otapw", HTTP_POST, handleOtaPw);
  s_server.on("/api/portal", HTTP_POST, handlePortal);
  s_server.on("/api/restart", HTTP_POST, handleRestart);
  s_server.on("/update", HTTP_GET, handleUpdatePage);
  s_server.on("/api/ghcheck", HTTP_GET, handleApiGhCheck);
  s_server.on("/api/ghupdate", HTTP_POST, handleApiGhUpdate);
  s_server.on("/update", HTTP_POST, handleUpdateDone, handleUpdateUpload);
  s_server.onNotFound(handleNotFound);
  s_server.begin();
}

void webLoop() { s_server.handleClient(); }
// ===== src/main.cpp =====
// ESP8266 Home Automation v1.0 — 4 relays + 4 switches, captive-portal WiFi,
// authenticated web UI + JSON API, event log, NTP, OTA. See README.md.
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiClient.h>


static const char* kDeviceName = DEVICE_NAME;

static const int kRelayPins[HA_CHANNELS] = HA_RELAY_PINS;
static const int kSwitchPins[HA_CHANNELS] = HA_SWITCH_PINS;

static ha::RelayBank s_relays;
static ha::SwitchBank s_switches;
static ha::LogStore s_log;
static ha::AuthStore s_auth;
static ha::ResetWindow s_resetWin;
static AppContext s_ctx;

static bool s_wifiUp = false;
static bool s_ntpOk = false;
static std::string s_otaPassword;
static int s_logPending = 0;
static bool s_portalRequested = false;
static bool s_rebootRequested = false;
static uint32_t s_sw0PressSince = 0;
static bool s_portalFiredForPress = false;

static ha::Every s_ntpTick(HA_NTP_INTERVAL_MS);
static ha::Every s_flushTick(HA_LOG_FLUSH_INTERVAL_MS);
static ha::Every s_pruneTick(86400000UL);
static ha::Every s_keepaliveTick(HA_KEEPALIVE_INTERVAL_MS);
static ha::Every s_wifiTick(5000);
static uint32_t s_downSince = 0;
static bool s_windowExpired = false;
static bool s_ghBootChecked = false;

static void persistAll() {
  uint8_t mask = 0;
  for (int i = 0; i < HA_CHANNELS; i++)
    if (s_relays.get(i)) mask |= (uint8_t)(1u << i);
  std::string r;
  r += (char)mask;
  fsWriteFile(HA_RELAY_FILE, r);
  fsWriteFile(HA_AUTH_FILE, s_auth.serialize());
  fsWriteFile(HA_LOG_FILE, s_log.dump());
  fsWriteFile(HA_OTAKEY_FILE, s_otaPassword);
}

static void addLog(const std::string& msg) {
  s_log.append(timeEpoch(), msg);
  s_logPending++;
}

static void applyRelayPin(int ch) {
  digitalWrite(kRelayPins[ch], s_relays.levelForChannel(ch));
}

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("ESP-Home " HA_VERSION " booting");

  if (!fsBegin(true)) Serial.println("FS mount failed!");

  // Unique salt per device so identical passwords hash differently.
  char salt[16];
  snprintf(salt, sizeof(salt), "esp-%08X", ESP.getChipId());
  s_auth.setSalt(salt);
  if (!s_auth.load(fsReadFile(HA_AUTH_FILE)))
    Serial.println("No auth store; first-boot setup required");

  s_log.configure(HA_LOG_MAX_BYTES, HA_LOG_MAX_AGE_DAYS);
  s_log.load(fsReadFile(HA_LOG_FILE));

  std::string ota = fsReadFile(HA_OTAKEY_FILE);
  if (!ota.empty() && ota.back() == '\n') ota.pop_back();
  s_otaPassword = ota;

  // Relays: pins first, then restore saved states.
  s_relays.configure(HA_CHANNELS, RELAY_ACTIVE_LOW != 0);
  for (int i = 0; i < HA_CHANNELS; i++) {
    pinMode(kRelayPins[i], OUTPUT);
    applyRelayPin(i);  // safe OFF before restore
  }
  std::string saved = fsReadFile(HA_RELAY_FILE);
  if (saved.size() == 1) {
    for (int i = 0; i < HA_CHANNELS; i++)
      if (saved[0] & (1 << i)) {
        s_relays.set(i, true);
        applyRelayPin(i);
      }
  }
  s_relays.onChange([](int ch, bool) {
    applyRelayPin(ch);
    uint8_t mask = 0;
    for (int i = 0; i < HA_CHANNELS; i++)
      if (s_relays.get(i)) mask |= (uint8_t)(1u << i);
    std::string r;
    r += (char)mask;
    fsWriteFile(HA_RELAY_FILE, r);  // persist on every change
  });

  // Switches: buttons to GND. GPIO16 needs its external 10k pull-up.
  s_switches.configure(HA_CHANNELS, HA_DEBOUNCE_MS, 0);
  for (int i = 0; i < HA_CHANNELS; i++) {
    if (kSwitchPins[i] == 16)
      pinMode(kSwitchPins[i], INPUT);
    else
      pinMode(kSwitchPins[i], INPUT_PULLUP);
  }

  // Context for the web layer.
  s_ctx.relays = &s_relays;
  s_ctx.switches = &s_switches;
  s_ctx.log = &s_log;
  s_ctx.auth = &s_auth;
  s_ctx.relayPins = kRelayPins;
  s_ctx.switchPins = kSwitchPins;
  s_ctx.channels = HA_CHANNELS;
  s_ctx.epochNow = []() { return timeEpoch(); };
  s_ctx.fmtTime = [](uint32_t e) { return timeFormat(e); };
  s_ctx.addLog = addLog;
  s_ctx.saveAll = persistAll;
  s_ctx.requestPortal = []() { s_portalRequested = true; };
  s_ctx.requestReboot = []() { s_rebootRequested = true; };
  s_ctx.wifiUp = &s_wifiUp;
  s_ctx.ntpOk = &s_ntpOk;
  s_ctx.otaPassword = &s_otaPassword;
  s_ctx.fwVersion = HA_VERSION;

  // Triple-reset recovery: N quick RESET presses -> wipe WiFi + portal.
  // The count lives in RTC memory: resets preserve it, power loss clears it.
  s_resetWin.configure(HA_RESET_COUNT, HA_RESET_WINDOW_MS);
  s_resetWin.loadCount(resetRecoveryCount());
  bool tripleReset = s_resetWin.noteBoot();
  resetRecoverySave(s_resetWin.count());

  // Network: portal fallback, then time, OTA, mDNS, web.
  if (tripleReset) {
    addLog("Triple-reset: WiFi erased, opening portal");
    Serial.println("Triple-reset recovery: erasing WiFi");
    WiFi.disconnect(true);
    wifiPortalOpen("ESP-Setup", HA_PORTAL_TIMEOUT_S);
    wifiPortalPoll();
    s_wifiUp = wifiIsUp();
    resetRecoveryClear();
    s_resetWin.clear();
    s_windowExpired = true;
  } else {
    s_wifiUp = wifiPortalBoot("ESP-Setup", HA_PORTAL_TIMEOUT_S);
  }
  Serial.print("WiFi: ");
  Serial.println(s_wifiUp ? wifiIp().c_str() : "offline");
  addLog(s_wifiUp ? "WiFi connected" : "WiFi offline; running standalone");

  timeSyncBegin();
  if (s_wifiUp && timeSyncForceUpdate()) {
    s_ntpOk = true;
    addLog("NTP synced");
  }
  s_log.prune(timeEpoch());

  otaBegin(kDeviceName, s_otaPassword);
  MDNS.begin(kDeviceName);
  webBegin(&s_ctx);
  Serial.println("Ready");
  addLog("Boot complete");
  persistAll();
}

static void pollSwitches() {
  uint32_t now = millis();
  for (int i = 0; i < HA_CHANNELS; i++) {
    bool raw = (digitalRead(kSwitchPins[i]) == LOW);  // pressed = GND
    ha::SwitchBank::Event e = s_switches.update(i, raw, now);
    if (e == ha::SwitchBank::PRESSED) {
      bool on = !s_relays.get(i);
      s_relays.set(i, on);  // callback drives pin + persists
      char msg[48];
      snprintf(msg, sizeof(msg), "Switch %d pressed -> Relay %d %s", i + 1,
               i + 1, on ? "ON" : "OFF");
      addLog(msg);
      if (i == 0) {
        s_sw0PressSince = now;
        s_portalFiredForPress = false;
      }
    }
    if (e == ha::SwitchBank::RELEASED && i == 0) s_sw0PressSince = 0;
  }
  // Hold switch 1 for 8 s -> open the WiFi config portal.
  if (s_sw0PressSince != 0 && !s_portalFiredForPress &&
      (uint32_t)(now - s_sw0PressSince) >= HA_PORTAL_TRIGGER_HOLD_MS) {
    s_portalFiredForPress = true;
    s_portalRequested = true;
    addLog("Portal requested (switch hold)");
  }
}

static void keepalive() {
  // Some hotspots drop idle clients: a brief TCP probe keeps the lease warm.
  WiFiClient c;
  if (!c.connect("google.com", 80)) {
    addLog("Keepalive probe failed");
    return;
  }
  c.print("HEAD / HTTP/1.0\r\nHost: google.com\r\n\r\n");
  c.stop();
}

void loop() {
  webLoop();
  otaLoop();
  MDNS.update();

  uint32_t now = millis();
  if (s_wifiTick.due(now)) {
    bool wasUp = s_wifiUp;
    wifiPortalPoll();
    s_wifiUp = wifiIsUp();
    if (s_wifiUp) {
      s_downSince = 0;
    } else {
      // Network-drop recovery: re-associate (rate-limited). No auto-reboot:
      // a dead router doesn't need one, and reboots blink the relays.
      if (wasUp) s_downSince = now;
      if (WiFi.SSID().length() > 0 &&
          (uint32_t)(now - s_downSince) >= HA_RECONNECT_AFTER_MS) {
        s_downSince = now;
        addLog("WiFi down 60s: reconnecting");
        WiFi.reconnect();
      }
    }
  }
  if (s_ntpTick.due(now) && s_wifiUp) {
    timeSyncLoop();
    s_ntpOk = timeIsValid();
  }
  if (s_pruneTick.due(now)) {
    s_log.prune(timeEpoch());
    persistAll();
  }
  if (s_keepaliveTick.due(now) && s_wifiUp) keepalive();
  if (s_flushTick.due(now) && s_logPending > 0) {
    fsWriteFile(HA_LOG_FILE, s_log.dump());
    s_logPending = 0;
  } else if (s_logPending >= HA_LOG_FLUSH_EVERY_N) {
    fsWriteFile(HA_LOG_FILE, s_log.dump());
    s_logPending = 0;
  }

  pollSwitches();

  // Reset window expired: slow boots are not button mashing.
  if (!s_windowExpired && now >= HA_RESET_WINDOW_MS) {
    s_windowExpired = true;
    resetRecoveryClear();
    s_resetWin.clear();
  }

  // One-shot GitHub update check shortly after boot (then on demand).
  if (!s_ghBootChecked && now >= 60000 && s_wifiUp) {
    s_ghBootChecked = true;
    std::string tag, url;
    if (ghCheckLatest(tag, url) &&
        ha::ghota::updateAvailable(HA_VERSION, tag)) {
      addLog("Update available: " + tag + " (see /update)");
    }
  }

  if (s_portalRequested) {
    s_portalRequested = false;
    addLog("Opening config portal");
    wifiPortalOpen("ESP-Setup", HA_PORTAL_TIMEOUT_S);
    s_wifiUp = wifiIsUp();
  }
  if (s_rebootRequested) {
    persistAll();
    resetRecoveryDisarm();  // intentional reboot, not a button press
    delay(300);
    ESP.restart();
  }
}
