#!/usr/bin/env python3
"""Concatenate the PlatformIO sources into a single Arduino-IDE sketch.

Usage: python3 tools/mirror_to_ino.py   (run from project root)
Output: arduino/ESP8266_Home_Automation/ESP8266_Home_Automation.ino

The .ino is generated — never edit it by hand. Edit src/ and re-run.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ORDER = [
    "src/common/sha256.h",
    "src/common/sha256.cpp",
    "src/logic/clock.h",
    "src/logic/relay.h",
    "src/logic/relay.cpp",
    "src/logic/debounce.h",
    "src/logic/debounce.cpp",
    "src/logic/logstore.h",
    "src/logic/logstore.cpp",
    "src/logic/auth.h",
    "src/logic/auth.cpp",
    "src/logic/scheduler.h",
    "src/config.h",
    "src/device/app_context.h",
    "src/device/fs_store.h",
    "src/device/fs_store.cpp",
    "src/device/time_sync.h",
    "src/device/time_sync.cpp",
    "src/device/wifi_portal.h",
    "src/device/wifi_portal.cpp",
    "src/device/ota_service.h",
    "src/device/ota_service.cpp",
    "src/device/web_ui.h",
    "src/device/web_ui.cpp",
    "src/main.cpp",
]

HEADER = """// ESP8266 Home Automation v1.0 — Arduino IDE sketch (GENERATED FILE).
// Generated by tools/mirror_to_ino.py from src/. Do not edit by hand.
//
// Install via Library Manager: WiFiManager (tzapu), NTPClient, Time (PaulStoffregen).
// Board: "Generic ESP8266 Module", Flash Size 4M, FS: LittleFS.
// Tweak the two defines below for your relay board, then upload.

#define RELAY_ACTIVE_LOW 1
#define DEVICE_NAME "esp-home"

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiClient.h>
#include <WiFiManager.h>
#include <NTPClient.h>
#include <TimeLib.h>
#include <ESP8266WebServer.h>
#include <Updater.h>
#include <ArduinoOTA.h>
#include <LittleFS.h>
#include <WiFiUdp.h>

// Forward declaration: the full definition is concatenated below
// (src/device/app_context.h). Needed because the IDE hoists function
// prototypes above the point where the struct is defined.
struct AppContext;

"""


def strip(path):
    out = []
    with open(os.path.join(ROOT, path)) as f:
        for line in f:
            s = line.strip()
            if s.startswith('#pragma once'):
                continue
            if s.startswith('#include "'):
                continue
            if s.startswith('#include <Arduino.h>'):
                continue
            out.append(line.rstrip("\n"))
    return "\n".join(out)


def main():
    parts = [HEADER.rstrip("\n")]
    for rel in ORDER:
        full = os.path.join(ROOT, rel)
        if not os.path.exists(full):
            print("MISSING: %s" % rel)
            return 1
        parts.append("// ===== %s =====" % rel)
        parts.append(strip(rel))
    body = "\n".join(parts) + "\n"
    if "void setup()" not in body or "void loop()" not in body:
        print("ERROR: generated sketch lacks setup()/loop()")
        return 1
    dest_dir = os.path.join(ROOT, "arduino", "ESP8266_Home_Automation")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, "ESP8266_Home_Automation.ino")
    with open(dest, "w") as f:
        f.write(body)
    print("wrote %s (%d bytes)" % (dest, len(body)))


if __name__ == "__main__":
    sys.exit(main())
